### ISSUE TITLE
cat: 'Emotion_labels/Emotion/*/*/*': No such file or directory

### ISSUE THREAD

**Issue by cy19980615** [estrm/onemove#1]
run the shell with error 
cat: 'Emotion_labels/Emotion/*/*/*': No such file or directory

but i have this directory ：Emotion_labels/Emotion

**Comment by estrm** [comment]
Hi cy19980615, the directory tree should look like (**pictured**), and **Emotion_labels** is the folder that unzipped by **Emotion_labels.zip**.

![2020-03-31 003743](https://user-images.githubusercontent.com/12713192/77938192-f44e3780-72e7-11ea-8a94-f522cc3542e2.png)

**Comment by estrm** [comment]
> run the shell with error
> cat: 'Emotion_labels/Emotion/_/_/*': No such file or directory
> 
> but i have this directory ：Emotion_labels/Emotion

Have you solved the problem?
